name: CI/CD Backend Express VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy Backend Express
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.APP_PATH }}

            git pull origin master

            export CI=true

            # INSTALL BACKEND ONLY
            pnpm install --filter backend-express --frozen-lockfile

            # START / RELOAD BACKEND
            pm2 reload inovasionline || pm2 start apps/backend-express/index.js --name inovasionline

            pm2 save
          EOF
